export const MM_SM = "(min-width: 640px)"
export const MM_MD = "(min-width: 768px)"
export const MM_LG = "(min-width: 1024px)"
export const MM_XL = "(min-width: 1280px)"
export const MM_2XL = "(min-width: 1536px)"
